# -*- coding: utf-8 -*-
"""FIN_UVA_UVI_USD (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LcaYak2h90FoStoO29l1CLWJMwyGjYnR

¿A qué inversión le fue mejor en lo que va del 2022, dólar blue, UVA o UVI?

En lo que va del año 2022 decidimos comparar cual es la inversión que mejores rendimientos trajo a aquellas personas que decidieron confiar sus ahorros en dólar blue, UVA o UVI. Antes que desplegar cualquier análisis debemos saber de qué se trata cada una de estas. 

UVI: Unidades de Vivienda es un sistema de ahorro en "ladrillos". Es una unidad que se ajusta en pesos indexada por el índice de costos la Construcción. Si bien también se puede utilizar para ajustar créditos hipotecarios, hoy la banca pública lo ofrece como una forma de ahorro en metros cuadrados de vivienda. En donde se ahorra en UVI y se calcula que cada 1.000 unidades se adquieren un metro de construcción.

UVA: Unidad de Valor Adquisitivo ajustada por el índice Coeficiente de Estabilización de Referencia (CER), que es elaborado por el Banco Central de la República Argentina (BCRA) para medir la evolución de la inflación tomando como base el Índice de Precios al Consumidor (IPC) del INDEC. Por lo tanto, cada UVA tiene un valor en pesos que aumenta por medio del CER.

Dólar blue es el mercado informal o no regulado de la divisa norteamericana. 

En el grafico se puede observar en el eje ‘X’ el paso de los meses del 2022 luego en el eje ‘Y’ los índices de UVA, UVI y dólar blue. Todos los incides arrancan el 100 para hacer más fácil su comparación, el desempeño de cada uno es variado dependiendo de la época del año, en algunos meses el dólar blue estuvo por encima de los otros dos índices. Pero hoy concretamente quien está en primer puesto   el índice UVA con 72 puntos arriba segundo lugar seguido UVI con 55 y en tercer puesto el índice dólar blue con 43. 

Debemos pensar y tener en cuenta algunas consideraciones a la hora de decidir qué tipo de inversión vamos a realizar Es posible que alguna necesidad surja y nos veamos forzados a deshacernos de alguna porción de nuestra inversión. La flexibilidad que tiene el dólar de convertir en pesos es casi inmediata sin ningún tipo de penalidad alguna más que la cotización del día. 

En cuanto a plazo mínimo es de 90 días para UVA y de 180 días para UVI. Con la posibilidad de cancelar recién transcurrido el primer mes completo, es decir poder darlo por finalizarlo para cobrar los intereses al día número 31 desde que se lo inicio.  

Luego de los puntos mencionados anteriormente es importante saber qué tipo de gastos vamos a tener y cuál podría ser nuestra necesidad de hacernos lo más rápidamente de nuestro dinero para poder utilizarlo. ¿En el caso de que surja un imprevisto, podríamos esperar un mes para cancelar un plazo fijo? Si la respuesta es sí, lo más probables es que deberíamos ver la forma de fraccionar nuestro plazo fijo. Creando varios con un mes de diferencia   para disponer de algún dinero si deseamos gastarlo. De lo contrario podríamos hacer el plazo fijo a un mayor plazo. Si ninguna de las dos opciones anteriores te da tranquilidad entonces será el dólar blue tu mejor opción. ¿Cuál es la mejor inversión para vos teniendo en cuenta tu situación? Como decimos siempre, hacelo personal, contanos   porque elegiste una opción y no otra.

# Proximos pasos 

* Desde cuando hay datos uva y uvis --> esta en el bcra principales variables.  
* markdown 
* Bucar de que forma voy a contar esta historia y a quienes puntualmente. 
   * Profe ingles (sueldo variable no alquila  )
   * Empleado sueldo fijo alquila.
   * Ahorrista de USD200 /mes 
   * Ahorrista con USD20000

* TODO 
  * Pasar UVA a % que todo quede en base 100
  * Hacer proximos pasos
  * Buscar dolar oficial 
  * Comparar si la infacion mensual se puede sacar de UVAs
  * Como sacar la inflacion mensaul de BCRA https://www.bcra.gob.ar/PublicacionesEstadisticas/Principales_variables_datos.asp
  * Ver la relacion entre aumento del blue y el oficial
  * inversiones disponibles monto y plazo  minimo.

#¿Tenés 5k y no sabés en dónde invertir?

¿A qué  inversión le fue mejor en lo que va del 2022, dólar blue, UVA o UVIS? 

En lo que va del año 2022 decidimos comparar cual es la inversión que mejores rendimientos trajo a aquellas personas que decidieron confiar sus ahorros en dólar blue, UVA o UVIS. Antes que desplegar cualquier análisis debemos saber de qué se trata cada una de estas.

UVI: Unidades de Vivienda es un sistema de ahorro en "ladrillos". Es una unidad que se ajusta en pesos indexada por el índice de costos la Construcción. Si bien también se puede utilizar para ajustar créditos hipotecarios, hoy la banca pública lo ofrece como una forma de ahorro en metros cuadrados de vivienda. En donde se ahorra en UVI y se calcula que cada 1.000 unidades se adquieren un metro de construcción.

UVA: Unidad de Valor Adquisitivo ajustada por el índice Coeficiente de Estabilización de Referencia (CER), que es elaborado por el Banco Central de la República Argentina (BCRA) para medir la evolución de la inflación tomando como base el Índice de Precios al Consumidor (IPC) del INDEC. Por lo tanto, cada UVA tiene un valor en pesos que aumenta por medio del CER ?

Dólar blue es el mercado informal o no regulado de la divisa norteamericana.
"""

!pip install --upgrade plotly
!pip install jupyter-dash #TODO: es necesario? Que suma?

import pandas as pd #U: leer y agrupar datos

import plotly.graph_objects as go #U: graficar con plotly
import plotly.express as px #U: graficar con plotly

from jupyter_dash import JupyterDash #TODO: como se usa? necesitamos? #VER: https://analyticsindiamag.com/how-to-use-plotly-in-colab/
from dash import dcc
from dash import html
from dash.dependencies import Input, Output

"""## Obtener los datos

Ya los extraemos del sitio de BCRA y los guardamos en data.podemosaprender.org

* TODO: se podrían extraer para más años.
* TODO: se pueden agregar los de GCBA de m2
* TODO: se pueden agregar salarios, RIPTE? 
"""

# creo tablas de UVIS
uvi_df_tables= pd.read_html('http://data.podemosaprender.org/finanzas/UVI_BCRA_2022.html')
uvi_df= uvi_df_tables[0] #A: sabemos que hay una sola
uvi_df

# creo tablas de UVAS
uva_df_tables= pd.read_html('http://data.podemosaprender.org/finanzas/UVA_BCRA_2022.html')
uva_df= uva_df_tables[0] #A: sabemos que hay una sola! PARA quer hace esto ?
uva_df

# creo tabla de dolar blue. Ojo!!! PQ   no tuve que usar la funcion pd.read_html 
usd_blue_df= pd.read_csv("https://data.podemosaprender.org/finanzas/USD_BLUE_2022.csv", sep="\t")
usd_blue_df

# me guardo el primer dato de la lista de dolar blue venta. Este seria mi dato cero con el cual comparo todos los demas
usd_blue_inicial = usd_blue_df['venta'][0]

#inicializo como valor 100 % el primer valor  
usd_blue_df['indice']=usd_blue_df['venta'] / usd_blue_inicial *100
usd_blue_df.rename(columns={'fecha':'Fecha'}, inplace=True)# cambio el nombre de la columna 'fecha' a 'Fecha' 
usd_blue_df

uvi_inicial = uvi_df['Valor'][0]

uvi_df['indice'] = uvi_df['Valor'] / uvi_inicial * 100
uvi_df

uva_inicial = uva_df['Valor'][0]

uva_df['indice']=uva_df['Valor']/uva_inicial*100
#uva_df.rename(columns={'fecha':'Fecha'}, inplace=True)
uva_df

#TODO: convertir todos en INDICES que valgan lo mismo en el primer dia ej. 100 y cambien proporcionalmente.
indices_df= pd.merge(uva_df, uvi_df, on="Fecha")
indices_df.rename(columns={'Valor_x':'UVA', 'Valor_y': 'UVI','indice_x':'UVA_index', 'indice_y':'UVI_index'}, inplace=True)

indices_df

"""
De aca para abajo vamos a unir todos los idices """

#TODO: convertir todos en INDICES que valgan lo mismo en el primer dia ej. 100 y cambien proporcionalmente.
indices_df= pd.merge(indices_df, usd_blue_df, on="Fecha")
indices_df.rename(columns={'indice':'i_USD'}, inplace=True)
indices_df

"""## Graficar una comparación básica

"""

fig = px.line(indices_df, x="Fecha", y=["UVA_index","UVI_index","i_USD"], title='Indice de precios Construcción (UVI) vs Consumidor (UVA) vs Dolar Blue')
fig.show()
#A: el grafico facilisimo y comodisimo que nos regala plotly <3 <3 <3

#TODO: mas avanzado pero lento de ejecutar
fig = px.line(uva_df, x="Fecha", y="Valor")

app = JupyterDash(__name__) #A: podemos crear una app dash aca mismo!
app.layout = html.Div([dcc.Graph(figure=fig)]) #A: armamos la app como siempre en dash, con html, controles, etc.
app.run_server(mode='inline') #A: ejecutar la app aqui mismo